# Linear Algebra

## Gaussian distribution

\begin{equation}
f(x) = \frac{1}{\sigma \sqrt{2 \pi}} e^\frac{-(x - \mu)^2}{2 \sigma^2}
\end{equation}

\begin{equation}
\mathbf{p} = 
  \begin{bmatrix}
    \mu \\
    \sigma
  \end{bmatrix}
\end{equation}

## Sum of Squared Residuals, SSR

\begin{equation}
\textbf{SSR} \left( \mathbf{p} \right) = \left| \mathbf{f} - \mathbf{g_p} \right|^2
\end{equation}

### Solving linear equation using the inverse Matrix

In [3]:
import numpy as np

A = [
    [4, 6, 2],
    [3, 4, 1],
    [2, 8, 13]
]
Ainv = np.linalg.inv(A)
print(Ainv)

s = [9, 7, 2]

r = np.linalg.solve(A, s)
print(r)

[[-3.14285714  4.42857143  0.14285714]
 [ 2.64285714 -3.42857143 -0.14285714]
 [-1.14285714  1.42857143  0.14285714]]
[ 3.  -0.5  0. ]


## Eigenvalues & Eigenvectors

In [1]:
import numpy as np

M = np.array([
    [1, 0, 0],
    [0, 2, 0],
    [0, 0, 3]
])
vals, vecs = np.linalg.eig(M)
# Eigenvalues
print('Eigenvalues:\n', vals)
# Eigenvectors - Note, the eigenvectors are the columns of the output.
print('Eigenvectors:\n', vecs)

Eigenvalues:
 [1. 2. 3.]
Eigenvectors:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [2]:
import numpy as np

M = np.array([
    [  4,   -5,  6],
    [  7,   -8,  6],
    [3/2, -1/2, -2]
])
vals, vecs = np.linalg.eig(M)
# Eigenvalues
print('Eigenvalues:\n', vals)
# Eigenvectors - Note, the eigenvectors are the columns of the output.
print('Eigenvectors:\n', vecs)

Eigenvalues:
 [ 1. -4. -3.]
Eigenvectors:
 [[-0.6882472  -0.66666667  0.40824829]
 [-0.6882472  -0.66666667 -0.40824829]
 [-0.22941573  0.33333333 -0.81649658]]


In [14]:
import numpy as np

L = np.array([
    [0, 0, 0, 1],
    [1, 0, 0, 0],
    [0, 1, 0, 0],
    [0, 0, 1, 0]
])
vals, vecs = np.linalg.eig(L)
# Eigenvalues
print('Eigenvalues:\n', vals)
# Eigenvectors - Note, the eigenvectors are the columns of the output.
print('Eigenvectors:\n', vecs)

Eigenvalues:
 [-1.00000000e+00+0.j  8.32667268e-17+1.j  8.32667268e-17-1.j
  1.00000000e+00+0.j]
Eigenvectors:
 [[ 5.00000000e-01+0.00000000e+00j  2.63941871e-16-5.00000000e-01j
   2.63941871e-16+5.00000000e-01j  5.00000000e-01+0.00000000e+00j]
 [-5.00000000e-01+0.00000000e+00j -5.00000000e-01+0.00000000e+00j
  -5.00000000e-01-0.00000000e+00j  5.00000000e-01+0.00000000e+00j]
 [ 5.00000000e-01+0.00000000e+00j -2.85804968e-18+5.00000000e-01j
  -2.85804968e-18-5.00000000e-01j  5.00000000e-01+0.00000000e+00j]
 [-5.00000000e-01+0.00000000e+00j  5.00000000e-01-1.34144886e-16j
   5.00000000e-01+1.34144886e-16j  5.00000000e-01+0.00000000e+00j]]


In [15]:
import numpy as np

L = np.array([
    [0.1, 0.1, 0.1, 0.7],
    [0.7, 0.1, 0.1, 0.1],
    [0.1, 0.7, 0.1, 0.1],
    [0.1, 0.1, 0.7, 0.1]
])
vals, vecs = np.linalg.eig(L)
# Eigenvalues
print('Eigenvalues:\n', vals)
# Eigenvectors - Note, the eigenvectors are the columns of the output.
print('Eigenvectors:\n', vecs)

Eigenvalues:
 [ 1.0000000e+00+0.j  -6.0000000e-01+0.j  -1.2490009e-16+0.6j
 -1.2490009e-16-0.6j]
Eigenvectors:
 [[ 5.00000000e-01+0.00000000e+00j  5.00000000e-01+0.00000000e+00j
   5.00000000e-01+0.00000000e+00j  5.00000000e-01-0.00000000e+00j]
 [ 5.00000000e-01+0.00000000e+00j -5.00000000e-01+0.00000000e+00j
   4.35081013e-18-5.00000000e-01j  4.35081013e-18+5.00000000e-01j]
 [ 5.00000000e-01+0.00000000e+00j  5.00000000e-01+0.00000000e+00j
  -5.00000000e-01+6.46083779e-17j -5.00000000e-01-6.46083779e-17j]
 [ 5.00000000e-01+0.00000000e+00j -5.00000000e-01+0.00000000e+00j
  -2.15906071e-17+5.00000000e-01j -2.15906071e-17-5.00000000e-01j]]


In [16]:
import numpy as np

A = np.array([
    [0, 1],
    [1, 0]
])
vals, vecs = np.linalg.eig(A)
# Eigenvalues
print('Eigenvalues:\n', vals)
# Eigenvectors - Note, the eigenvectors are the columns of the output.
print('Eigenvectors:\n', vecs)

Eigenvalues:
 [ 1. -1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [17]:
import numpy as np

A = np.array([
    [3/2, -1],
    [-1/2, 1/2]
])
vals, vecs = np.linalg.eig(A)
# Eigenvalues
print('Eigenvalues:\n', vals)
# Eigenvectors - Note, the eigenvectors are the columns of the output.
print('Eigenvectors:\n', vecs)

Eigenvalues:
 [1.8660254 0.1339746]
Eigenvectors:
 [[ 0.9390708   0.59069049]
 [-0.34372377  0.80689822]]
